//
//  main.cpp
//  BlackJack
//
//  Created by Roy Ataya on 2018-08-30.
//  Copyright © 2018 Roy Ataya. All rights reserved.
//

#include <iostream>
#include <algorithm>
#include <vector>
#include <ctime>
#include <cstdlib>
using namespace std;

vector<string> deck;
vector<string> hand;
vector<string> dealer;
int menu();
void ClearScreen();
int randomNum(int num);
void DeckSetUp();
void gamePlay();
int randShuffle(int i);
void dealCard();

int main() {
    menu();
    ClearScreen();
    gamePlay();
    cout << endl << endl;
    return 0;
}

int randShuffle(int i) {
    srand(time(NULL));
    return rand()%i;
}

int randomNum(int num){
    int randNum = 0;
    srand(time(NULL)); // using the time function to get a seed for the srand function allows me to have a truly somewhat randomn number generated by rand()
    return randNum = rand() % num + 1; // generates a random number between 1 and num
}

void DeckSetUp(){
    deck = {"Ace of hearts","2 of hearts","3 of hearts","4 of hearts","5 of hearts","6 of hearts","7 of hearts","8 of hearts","9 of hearts","10 of hearts","J of hearts","Q of hearts","K of hearts","Ace of diamonds","2 of diamonds","3 of diamonds","4 of diamonds","5 of diamonds","6 of diamonds","7 of diamonds","8 of diamonds","9 of diamonds","10 of diamonds","J of diamonds","Q of diamonds","K of diamonds","Ace of spades","2 of spades","3 of spades","4 of spades","5 of spades","6 of spades","7 of spades","8 of spades","9 of spades","10 of spades","J of spades","Q of spades","K of spades","Ace of clubs","2 of clubs","3 of clubs","4 of clubs","5 of clubs","6 of clubs","7 of clubs","8 of clubs","9 of clubs","10 of clubs","J of clubs","Q of clubs","K of clubs"};
    
    random_shuffle(deck.begin(), deck.end(), randShuffle);
}

void dealCard(int n){
    int i = 0;
    i = randomNum(n);
    hand.push_back(deck[i]);
    cout << deck[i] << "    ";
    deck.erase(deck.begin()+i);
}

void gamePlay(){
    cout << "because this is a text based game the suite of a card is denoted by the lower case letter next to the number ex: 9c is the 9 of clubs, Jh is the jack of hearts" << endl << endl;
    DeckSetUp();
    
    int num = 0;
    int playerSum = 0;
    int dealerSum = 0;
    num = deck.size(); // number of cards in the deck
    for (int j = 0; j < 2; j++) {
        dealCard(num);
        num = num - 1;
    }
    
    char choice = '\0';
    bool exit = false;
    do {
        cout << "\n[h] to hit \n";
        cout << "[s] to stay \n";
        cout << "Choice: ";
        cin >> choice;
        choice = tolower(choice);
        if (choice == 's') {
            exit = true;
        }
        else if (choice == 'h'){
            for (int j = 0; j < hand.size(); j++) {
                cout << hand[j] << "    ";
            }
            dealCard(num);
            
        }
        else{
            cout << "Not a valid choice, try again\n";
        }
        cout << endl;
    } while (exit == false);
    
    
}

void ClearScreen() {cout << string( 10000, '\n' );}

int menu(){
    char choice = '\0';
    bool exit = false;
    do {
        cout << "[1] to play BlackJack\n";
        cout << "[0] to exit \n";
        cout << "Choice: ";
        cin >> choice;
        if (choice == '1' || choice == '0') {
            exit = true;
        }
        else{
            cout << "Not a valid choice, try again\n";
        }
    } while (exit == false);
    return 0;
}
